language: jp
pipeline:
  - name: "JapaneseTokenizer"
  - name: LexicalSyntacticFeaturizer
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "DIETClassifier"
    epochs: 100
    batch_strategy: sequence
    
policies:
  - name: "FallbackPolicy"
    nlu_threshold: 0.4
    core_threshold: 0.3
    fallback_action_name: 'action_custom_fallback'
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
